- name: Install required IRC server packages
  ansible.builtin.command: 'pkg install -y unreal anope'
  changed_when: true

- name: Configure UnrealIRCd
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/unreal/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/unreal" }}'
  when: item.state == 'file'

- name: Configure anope
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/anope/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/anope" }}'
  when: item.state == 'file'
