- name: Install UnrealIRCd
  ansible.builtin.command: 'pkg install -y unreal'
  changed_when: true

- name: Configure UnrealIRCd
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/unreal/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/unreal" }}'
  when: item.state == 'file'
