- name: Install required IRC server packages
  ansible.builtin.command: 'pkg install -y unreal anope'
  changed_when: true

- name: Configure UnrealIRCd
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/unreal/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/unreal" }}'
  when: item.state == 'file'

- name: Copy TLS certificate to UnrealIRCd conf folder
  ansible.builtin.copy:
    src: '/etc/ssl/{{ fqdn }}.crt.pem'
    remote_src: true
    dest: /usr/local/etc/unreal/tls/server.cert.pem
    owner: ircd
    group: ircd
    mode: '0644'

- name: Copy TLS private key to UnrealIRCd conf folder
  ansible.builtin.copy:
    src: '/etc/ssl/{{ fqdn }}.key.pem'
    remote_src: true
    dest: /usr/local/etc/unreal/tls/server.key.pem
    owner: ircd
    group: ircd
    mode: '0600'

- name: Configure anope
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/anope/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/anope" }}'
  when: item.state == 'file'
