- name: "Install useful testing and debug packages"
  ansible.builtin.command: 'pkg install -y tmux wget htop tree'
  changed_when: true

- name: "Create siva user"
  ansible.builtin.user:
    name: siva
    append: true
    groups: wheel

- name: "Add control host's ssh key to siva"
  ansible.posix.authorized_key:
    user: siva
    key: "{{ lookup('file', '/home/siva/.ssh/id_ed25519.pub') }}"
    exclusive: true

- name: "Configure tmux"
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/siva/.tmux.conf
    mode: '0644'
    owner: siva
    group: siva

- name: "Install script to reset to fresh install"
  ansible.builtin.copy:
    src: reset_to_fresh_install.sh
    dest: /home/siva/reset_to_fresh_install.sh
    mode: '0755'
    owner: siva
    group: siva
