# TODO mlmmj port should create mlmmj user and spooldir
# =====================================================
- name: Add mlmmj user for postfix transport
  ansible.builtin.user:
    name: mlmmj
    comment: Mlmmj Transport
    home: /var/spool/mlmmj
    shell: /usr/sbin/nologin
    create_home: false
  register: setup_jail_smtp_mlmmj_user

- name: Create mlmmj spool directory in jailhost
  ansible.builtin.file:
    path: /empt/synced/rw/mlmmj_spool
    state: directory
    mode: '0700'
    owner: '{{ setup_jail_smtp_mlmmj_user.uid }}'
    group: '{{ setup_jail_smtp_mlmmj_user.uid }}'
  delegate_to: jailhost

- name: Create empty mountpoint for mlmmj spool
  ansible.builtin.file:
    path: /var/spool/mlmmj
    state: directory
    mode: '0700'
    owner: mlmmj
    group: mlmmj

- name: Nullfs mount the mlmmj spool storage
  ansible.posix.mount:
    fstab: /empt/synced/rw/fstab.d/smtp.fstab
    src: /empt/synced/rw/mlmmj_spool
    path: /empt/jails/smtp/var/spool/mlmmj
    fstype: nullfs
    opts: rw
    state: mounted
  delegate_to: jailhost
# =====================================================

- name: Create postfix spool directory in jailhost temporarily with chown root
  ansible.builtin.file:
    path: /empt/synced/postfix_spool
    state: directory
    mode: '0755'
    owner: root
    group: wheel
  delegate_to: jailhost

- name: Create empty mountpoint for postfix spool
  ansible.builtin.file:
    path: /var/spool/postfix
    state: directory
    mode: '0755'
    owner: root
    group: wheel

- name: Nullfs mount the postfix spool storage
  ansible.posix.mount:
    fstab: /empt/synced/rw/fstab.d/smtp.fstab
    src: /empt/synced/postfix_spool
    path: /empt/jails/smtp/var/spool/postfix
    fstype: nullfs
    opts: rw
    state: mounted
  delegate_to: jailhost

- name: Install smtp jail required ports
  ansible.builtin.command: pkg -r /empt/jails/smtp install -y postfix mlmmj
  delegate_to: jailhost
  changed_when: true

- name: Refresh ldconfig
  ansible.builtin.service:
    name: ldconfig
    state: started

- name: Query new postfix user
  ansible.builtin.user:
    name: postfix
  register: setup_jail_smtp_postfix_user

- name: Change ownership and permissions on postfix spool data and mountpoint directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
    owner: '{{ setup_jail_smtp_postfix_user.uid }}'
    group: '{{ setup_jail_smtp_postfix_user.uid }}'
  loop:
    - /empt/synced/postfix_spool
    - /empt/jails/smtp/var/spool/postfix

- name: Configure postfix
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/postfix/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/postfix" }}'
  when: item.state == 'file'

- name: Initialize empty mlmmj transport and alias databases
  ansible.builtin.file:
    path: '/usr/local/etc/postfix/{{ item }}'
    state: touch
    mode: '0644'
  loop:
    - mlmmj_transport
    - mlmmj_aliases

# TODO cdb maps and aliases
- name: Generate postfix maps
  ansible.builtin.command: 'postmap /usr/local/etc/postfix/{{ item }}'
  loop:
    - mlmmj_transport
    - mlmmj_aliases
  register: setup_jail_smtp_postmap
  changed_when: setup_jail_smtp_postmap.rc == 0

- name: Generate aliases database
  ansible.builtin.command: postalias cdb:/etc/mail/aliases
  register: setup_jail_smtp_postalias
  changed_when: setup_jail_smtp_postalias.rc == 0

- name: Configure PAM with krb5 for cyrus saslauthd
  ansible.builtin.copy:
    content: |
      auth required pam_krb5.so
      account required pam_nologin.so
    dest: /etc/pam.d/smtp
    mode: '0644'
    owner: root
    group: wheel

- name: Create cyrus sasl configuration directory
  ansible.builtin.file:
    path: /usr/local/etc/sasl2
    state: directory
    mode: '0755'
    owner: root
    group: wheel

- name: Configure cyrus sasl for postfix smtpd
  ansible.builtin.copy:
    content: |
      pwcheck_method: auxprop saslauthd
    dest: /usr/local/etc/sasl2/smtpd.conf
    mode: '0644'
    owner: root
    group: wheel

- name: Ensure keytab can only be read by postfix
  ansible.builtin.file:
    path: /etc/krb5.keytab
    mode: '0400'
    owner: postfix
    group: postfix

- name: Add mlmmj maintenance task to cron
  ansible.builtin.cron:
    user: mlmmj
    name: check cpu usage
    job: -n -q /usr/local/bin/mlmmj-maintd -F -d /var/spool/mlmmj

- name: Enable and start smtp services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - postfix
    - saslauthd
    - cron
