image: alpine/edge
packages:
  - ansible-lint
tasks:
  - lint: |
      cd empt/ansible
      ansible-galaxy install -r requirements.yml
      cp remote_inventory.ini.sample remote_inventory.ini
      cp org_vars.yml.sample org_vars.yml
      find . -type f -name '*.yml' | xargs ansible-lint
