- name: Add jail to the inventory
  ansible.builtin.add_host:
    name: 'jail_{{ jail.name }}'
    ansible_host: '{{ jail.ipaddr }}'
    groups:
      - jails

- name: Create jail's install directory
  ansible.builtin.file:
    path: '{{ jailroot }}'
    state: directory
    mode: '0755'

- name: Unarchive (thick) base jail to installed location
  ansible.builtin.unarchive:
    src: /tmp/base.tar.xz
    remote_src: true
    dest: '{{ jailroot }}'

- name: Populate common /etc files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/jail/guests/{{ jail.name }}/etc/{{ item.path | replace(".j2", "")}}'
    mode: '0644'
  with_community.general.filetree: templates/common_etc/
  when: item.state == 'file'

- name: Create the common fstabs
  ansible.builtin.template:
    src: common_fstab.j2
    dest: '/usr/jail/fstabs/{{ jail.name }}'
    owner: root
    group: wheel
    mode: '0644'

- name: Run as much jail-specific setup as possible using the host connection
  ansible.builtin.include_role:
    name: 'host_setup_jail_{{ jail.name }}'
