- name: Create all missing directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /tmp/base_jail
    - /usr/jail/fstabs
    - /usr/jail/guests
    - /usr/local/etc/pkg/repos
    - /usr/local/poudriere_repo

- name: Set poudriere pkg repo
  ansible.builtin.copy:
    content: |
      Poudriere: {
        url: "file:///usr/local/poudriere_repo"
      }
      FreeBSD: {
        enabled: no
      }
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'

- name: Extract poudriere repo archive
  ansible.builtin.unarchive:
    src: '{{ inventory_hostname }}-poudriere.tar.zst'
    dest: /usr/local/poudriere_repo

- name: Reinstall all previously upstream mirror installed packages from poudriere
  ansible.builtin.command: 'pkg install -r Poudriere -f -y python doas gtar unzip'
  changed_when: true

- name: Download FreeBSD base system archive to local filesystem
  ansible.builtin.get_url:
    url: 'https://download.freebsd.org/ftp/releases/amd64/{{ freebsd_version }}/base.txz'
    dest: /tmp/base.tar.xz
    owner: root
    group: wheel
    mode: '0600'

- name: Populate jail.conf
  ansible.builtin.template:
    src: jail.conf.j2
    dest: /etc/jail.conf
    owner: root
    group: wheel
    mode: '0644'

- name: Run common setup tasks on all jails
  ansible.builtin.include_tasks: each_jail.yml
  vars:
    jail: '{{ each_jail_item }}'
    jailroot: '/usr/jail/guests/{{ each_jail_item.name }}'
  loop: '{{ all_jails }}'
  loop_control:
    loop_var: each_jail_item

- name: Start all barebones jails
  ansible.builtin.service:
    name: jail
    state: started

- name: Stop all barebones jails
  ansible.builtin.service:
    name: jail
    state: stopped

- name: debug
  tags: test
  ansible.builtin.debug:
    msg: '{{ hostvars }}'
