- name: Create storage dataset for all helpdesk data
  community.general.zfs:
    name: zroot/empt/helpdeskbot
    state: present
    extra_zfs_properties: '{{ zrep_dataset_props["zroot/empt/helpdeskbot"] }}'
  delegate_to: jailhost

# TODO turn this into a FreeBSD ports pkg
# =======================================
- name: Copy jailhost ansible inventory to helpdeskbot dataset
  ansible.builtin.copy:
    src: '{{ inventory_file }}'
    dest: /empt/helpdeskbot/inventory.ini
    owner: root
    group: wheel
    mode: '0600'
  delegate_to: jailhost

- name: Copy jailhost root-owned helpdesk scripts to helpdeskbot dataset
  ansible.builtin.template:
    src: ssh-forced-helpdeskbot.j2
    dest: /empt/helpdeskbot/ssh-forced-helpdeskbot
    owner: root
    group: wheel
    mode: '0700'
  delegate_to: jailhost

- name: Install helpdesk ansible playbooks
  ansible.builtin.copy:
    src: playbooks
    dest: /empt/helpdeskbot/playbooks
    mode: '0700'
    owner: root
    group: wheel
  delegate_to: jailhost
# =======================================

- name: Create system account for the helpdeskbot in the helpdesk jail
  ansible.builtin.user:
    name: helpdeskbot
    comment: Helpdesk Robot
    shell: /usr/sbin/nologin
    home: /home/helpdeskbot
    create_home: true
# TODO find a way to create a globally unique UID, currently hardcoding
    uid: 21891
    generate_ssh_key: true
    ssh_key_type: ed25519
  register: setup_jail_helpdeskbot_user

- name: Create mail delivery local account for the helpdeskbot in the mail jail
  ansible.builtin.user:
    name: helpdeskbot
    comment: Helpdesk Robot
    shell: /usr/sbin/nologin
    home: /home/helpdeskbot
    create_home: true
    uid: '{{ setup_jail_helpdeskbot_user.uid }}'
  delegate_to: mail

- name: Create maildir directory layout under helpdeskbot home
  ansible.builtin.file:
    name: '/empt/helpdeskbot/{{ item }}'
    state: directory
    recurse: true
    mode: '0700'
    owner: '{{ setup_jail_helpdeskbot_user.uid }}'
    group: '{{ setup_jail_helpdeskbot_user.uid }}'
  loop:
    - home/mail/cur
    - home/mail/new
    - home/mail/tmp
    - playbooks
  delegate_to: jailhost

- name: Add helpdeskbot maildir directory nullfs mount to mail jail
  ansible.posix.mount:
    fstab: /empt/etc/mail/fstab
    src: /empt/helpdeskbot/home/mail
    path: /empt/jails/mail/home/helpdeskbot/mail
    fstype: nullfs
    opts: rw
    state: mounted
  delegate_to: jailhost

- name: Add helpdeskbot home directory nullfs mount to helpdesk jail
  ansible.posix.mount:
    fstab: /empt/etc/helpdesk/fstab
    src: /empt/helpdeskbot/home
    path: /empt/jails/helpdesk/home/helpdeskbot
    fstype: nullfs
    opts: rw
    state: mounted
  delegate_to: jailhost

- name: Ensure helpdeskbot maildir nullfs mountpoint has correct permissions in mail jail
  ansible.builtin.file:
    name: /home/helpdeskbot/mail
    state: directory
    mode: '0700'
    owner: helpdeskbot
    group: helpdeskbot
  delegate_to: mail

- name: Ensure helpdeskbot home nullfs mountpoint has correct permissions in helpdesk jail
  ansible.builtin.file:
    name: /home/helpdeskbot
    state: directory
    mode: '0700'
    owner: helpdeskbot
    group: helpdeskbot

- name: Authorize helpdeskbot ssh key on jailhost for receiving helpdesk play commands
  ansible.posix.authorized_key:
    user: root
    key: '{{ setup_jail_helpdeskbot_user.ssh_public_key }}'
    key_options: 'command="/empt/helpdeskbot/ssh-forced-helpdeskbot $SSH_ORIGINAL_COMMAND"'
  delegate_to: jailhost

- name: Retrieve jailhost ssh host public key
  ansible.builtin.command: ssh-keyscan -t ed25519 ::1
  changed_when: false
  delegate_to: jailhost
  register: setup_jail_helpdesk_host_pubkeys

- name: Add jailhost ssh host public keys to known_hosts
  ansible.builtin.lineinfile:
    path: /home/helpdeskbot/.ssh/known_hosts
    create: true
    line: '{{ item }}'
    mode: '0600'
    owner: helpdeskbot
    group: helpdeskbot
  loop: '{{ setup_jail_helpdesk_host_pubkeys.stdout_lines | flatten(levels=1) }}'

- name: Install fdm configuration
  ansible.builtin.template:
    src: fdm.conf.j2
    dest: /home/helpdeskbot/.fdm.conf
    mode: '0600'
    owner: helpdeskbot
    group: helpdeskbot
    validate: fdm -f %s -n

- name: Set crontab MAILTO
  ansible.builtin.cron:
    user: helpdeskbot
    env: true
    name: MAILTO
    job: 'it@{{ org_domain }}'

- name: Setup crontab to periodically process helpdesk queue
  ansible.builtin.cron:
    user: helpdeskbot
    name: process helpdeskbot queue with fdm
    job: fdm -a helpdeskbot -l fetch

- name: Subscribe the helpdesk and IT staff to the helpdesk mailing list
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/helpdesk -a {{ item }}@{{ org_domain }} -c -f -s'
  loop:
    - it
    - helpdeskbot
  delegate_to: mail
  register: setup_jail_helpdesk_mlmmj_sub_output
  changed_when: setup_jail_helpdesk_mlmmj_sub_output.rc == 0
