- name: Install nsd port from poudriere
  ansible.builtin.command: 'pkg install -r /usr/jail/guests/{{ jail.name }} -y nsd'

- name: Configure nsd and DNS zones
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/nsd/{{ item.path | replace(".j2", "")}}'
    mode: '0644'
  with_filetree: 'nsd/'
  when: item.state == 'file'

- name: Enable nsd service
  ansible.builtin.service:
    name: nsd
    enabled: yes
