- name: Install jailhost required packages
  ansible.builtin.command: pkg install -y cpu-microcode nagios-plugins rsync fdm py311-cryptography
  changed_when: true

# TODO query intel or AMD, currently hardcoding for wyse
- name: Enable early CPU microcode update at boot
  ansible.builtin.blockinfile:
    path: /boot/loader.conf
    block: |
      cpu_microcode_load="YES"
      cpu_microcode_name="/boot/firmware/amd-ucode.bin"

# TODO audit file permissions one by one
- name: Populate jailhost /etc files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/etc/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
    owner: root
    group: wheel
  with_community.general.filetree: '{{ "templates/jailhost_etc/" }}'
  when: item.state == 'file'

- name: Populate jailhost /usr/local/etc files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
    owner: root
    group: wheel
  with_community.general.filetree: '{{ "templates/jailhost_usr_local_etc/" }}'
  when: item.state == 'file'

- name: Create empty directory for base jail
  ansible.builtin.file:
    path: /tmp/base_jail
    state: directory
    mode: '0755'
    owner: root
    group: wheel

- name: Install pkgbase to temporary base jail
  ansible.builtin.command: pkg --rootdir /tmp/base_jail install -y --repository jail_pkgbase -g 'FreeBSD-*'
  changed_when: true

- name: Create all missing directories in base jail
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /tmp/base_jail/home
    - /tmp/base_jail/usr/local/etc/pkg/repos
    - /tmp/base_jail/usr/local/poudriere_repos
    # TODO don't use root for ssh between systems
    - /tmp/base_jail/root/.ssh

- name: Populate common /etc files into base jail
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/tmp/base_jail/etc/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
    owner: root
    group: wheel
  with_community.general.filetree: '{{ "templates/common_etc/" }}'
  when: item.state == 'file'

- name: Configure jail to use jail pkgbase and ports
  ansible.builtin.copy:
    content: |
      pkgbase: {
        url: "file:///usr/local/poudriere_repos/jail_pkgbase"
        enabled: yes
      }

      ports: {
        url: "file:///usr/local/poudriere_repos/ports"
        enabled: yes
      }

      FreeBSD: {
        url: "pkg+https://pkg.FreeBSD.org/${ABI}/latest",
        mirror_type: "srv",
        signature_type: "fingerprints",
        fingerprints: "/usr/share/keys/pkg",
        enabled: no
      }
    dest: /tmp/base_jail/usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0600'

- name: Create top level dataset for empt
  community.general.zfs:
    name: zroot/empt
    state: present
    extra_zfs_properties:
      mountpoint: /empt

# TODO benchmark lz4 (default) vs no compression here
- name: Create ZFS dataset for all non-synced jail storage
  community.general.zfs:
    name: zroot/empt/jails
    state: present

- name: Create dataset for all synced (replicated with backup) data
  community.general.zfs:
    name: zroot/empt/synced
    state: present

- name: Create synced dataset for non-executable compressed data
  community.general.zfs:
    name: zroot/empt/synced/rw
    state: present
    extra_zfs_properties: '{{ zrep_synced_dataset_properties["zroot/empt/synced/rw"] }}'

- name: Populate rough EMPT directory structure
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: root
    group: wheel
  loop:
    - /empt/synced/bin
    - /empt/synced/rw/fstab.d
    - /empt/synced/rw/groups
    - /empt/synced/rw/humans
    - /empt/synced/rw/jail.conf.d
    - /empt/synced/rw/krb5data

- name: Prepare directories for jail nullfs-mounted logs and etc
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: root
    group: wheel
  loop: '{{ ["/empt/synced/rw/logs/", "/empt/synced/etc/"] | product(groups["jails"]) | map("join") }}'

- name: Install all jail.conf files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/empt/synced/rw/jail.conf.d/{{ item.path | replace(".j2", "") }}'
    mode: '0600'
    owner: root
    group: wheel
  with_community.general.filetree: '{{ "templates/jail.conf.d" }}'
  when: item.state == 'file'

- name: Create an fstab for every jail
  ansible.builtin.copy:
    # TODO is it possible to mount the jail /etc as 'ro'? it seems better
    content: |
      /usr/local/poudriere_repos /empt/jails/{{ item }}/usr/local/poudriere_repos nullfs ro 0 0
      /empt/synced/rw/logs/{{ item }} /empt/jails/{{ item }}/var/log nullfs rw 0 0
      /empt/synced/etc/{{ item }} /empt/jails/{{ item }}/etc nullfs rw 0 0
    dest: '/empt/synced/rw/fstab.d/{{ item }}.fstab'
    mode: '0600'
    owner: root
    group: wheel
  loop: '{{ groups["jails"] }}'

- name: Copy base jail /etc to synced jail etc directory under EMPT
  # NOTE the trailing slash on /tmp/base_jail/etc/ is required to copy its contents
  # rather than the entire directory. See cp(1).
  ansible.builtin.command: 'cp -a /tmp/base_jail/etc/ /empt/synced/etc/{{ item }}'
  loop: '{{ groups["jails"] }}'
  changed_when: true

- name: Remove /etc from base jail
  ansible.builtin.file:
    path: /tmp/base_jail/etc
    state: absent

- name: Clone (thick) base jail to installed locations
  # NOTE the trailing slash on /tmp/base_jail/ is required to copy its contents
  # rather than the entire directory. See cp(1).
  ansible.builtin.command: 'cp -a /tmp/base_jail/ /empt/jails/{{ item }}'
  loop: '{{ groups["jails"] }}'
  changed_when: true

# NOTE needed to clear immutable flags
- name: Clear all flags in temporary base jail tree
  ansible.builtin.command: chflags -R 0 /tmp/base_jail
  changed_when: true

- name: Remove temporary base jail
  ansible.builtin.file:
    path: /tmp/base_jail
    state: absent
