- name: Create all missing directories on jailhost
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /tmp/base_jail
    - /usr/jail/fstabs
    - /usr/jail/guests
  tags: always

# TODO move back to downloading from freebsd.org once fully tested
#- name: Download FreeBSD base system archive to local filesystem
#  ansible.builtin.get_url:
#    url: 'https://download.freebsd.org/ftp/releases/amd64/{{ freebsd_version }}/base.txz'
#    dest: /tmp/base.tar.xz
#    owner: root
#    group: wheel
#    mode: '0644'
#  tags: initial

- name: Unarchive (thick) base jail to temporary location
  ansible.builtin.unarchive:
    src: base.tar.xz
    dest: /tmp/base_jail
  tags: initial

- name: Create all missing directories in base jail
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /tmp/base_jail/usr/local/etc/pkg/repos
    - /tmp/base_jail/usr/local/poudriere_repo
    - /tmp/base_jail/root/.ssh
  tags: always

- name: Populate common /etc files into base jail
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/tmp/base_jail/etc/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
    owner: root
    group: wheel
  with_community.general.filetree: '{{ "templates/common_etc/" }}'
  when: item.state == 'file'
  tags: always

- name: Copy pkg repo config to base jail
  ansible.builtin.copy:
    src: /usr/local/etc/pkg/repos/FreeBSD.conf
    remote_src: true
    dest: /tmp/base_jail/usr/local/etc/pkg/repos/
    mode: '0644'
    owner: root
    group: wheel
  tags: always

- name: Add control host's ssh key to base jail
  ansible.posix.authorized_key:
    user: root
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINqa5qTRGfyJckSBOXWyqdSC4tortF5Nc0O6kQFkORFi siva@think"
    path: /tmp/base_jail/root/.ssh/authorized_keys
    exclusive: true
  tags: always

- name: Clone (thick) base jail to installed locations
  ansible.builtin.copy:
    src: /tmp/base_jail/
    remote_src: true
    dest: '/usr/jail/guests/{{ hostvars[item].inventory_hostname_short }}/'
  loop: '{{ groups["jails"] }}'
  tags: always

- name: Populate jail.conf
  ansible.builtin.template:
    src: jail.conf.j2
    dest: /etc/jail.conf
    owner: root
    group: wheel
    mode: '0644'
  tags: always

- name: Copy the common fstab for each jail
  ansible.builtin.template:
    src: common_fstab.j2
    dest: '/usr/jail/fstabs/{{ hostvars[item].inventory_hostname_short }}.fstab'
    owner: root
    group: wheel
    mode: '0644'
  vars:
    setup_jailhost_jail: '{{ item }}'
  loop: '{{ groups["jails"] }}'
  tags: always

- name: Add all jails to jailhost's /etc/hosts
  ansible.builtin.template:
    src: common_etc/hosts.j2
    dest: /etc/hosts
    mode: '0644'
  tags: always

# TODO enable once everything is figured out
# - name: Enable jail service
#   ansible.builtin.service:
#     name: jail
#     enabled: true
#   tags: always
#
# - name: Set list of enabled jails
#   ansible.builtin.lineinfile:
#     path: /etc/rc.conf
#     line: 'jail_list="certauth"'
#   tags: always

# TODO unnecessary for now since we've hardcoded IP addresses.
# Commenting out for now.
# - name: Add all jails to the inventory
#   ansible.builtin.add_host:
#     name: 'jail_{{ item.name }}'
#     ansible_host: '{{ item.ipaddr }}'
#     groups:
#       - jails
#   loop: '{{ all_jails }}'
#   tags: always

# TODO file an ansible bug: ansible.builtin.service doesn't start the jail
# service
- name: Start all enabled jails
  ansible.builtin.command: 'service jail onerestart'
  tags: always

# TODO pending on 'https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271069'
- name: WORKAROUND restart all services inside each jail for good measure
  ansible.builtin.shell: 'jls name | xargs -L1 -I% service -j % {{ item }} restart'
  loop:
    - syslogd
    - sshd
  tags: always
