- name: Install cifs required ports
  ansible.builtin.command: pkg -j cifs install -y samba419
  changed_when: true

- name: Install dns required ports
  ansible.builtin.command: pkg -j dns install -y nsd
  changed_when: true

# - name: Install kerberos required ports
#   ansible.builtin.command: pkg -j kerberos install -y heimdal-devel
#   changed_when: true

