- name: Create system account for monitoring all empt services
  ansible.builtin.user:
    name: emptmonitor
    comment: EMPT Monitor Agent
    shell: /usr/sbin/nologin
    home: /nonexistent
    create_home: false

- name: Authorize emptmonitor with doas to run monitoring script
  ansible.builtin.lineinfile:
    path: /usr/local/etc/doas.conf
    line: 'permit nopass emptmonitor cmd /usr/local/libexec/empt/monitor'
    create: true
    mode: '0600'
    owner: root
    group: wheel

- name: Setup crontab with to run monitoring
  ansible.builtin.cron:
    user: emptmonitor
    name: check load average
    job: -n -q /usr/local/libexec/empt/monitor every_minute
