- name: Install samba port
  ansible.builtin.command: 'pkg install -y {{ setup_jail_cifs_samba_package }}'
  changed_when: true

- name: Configure samba
  ansible.builtin.template:
    src: smb4.conf.j2
    dest: /usr/local/etc/smb4.conf
    mode: '0644'
    owner: root
    group: wheel
    validate: '/usr/local/bin/testparm --suppress-prompt %s'

- name: Allow KDC to accept auth requests from samba with no PAC
  ansible.builtin.command: 'kadmin --local modify --attributes=no-auth-data-reqd cifs/cifs.{{ org_domain }}'
  delegate_to: kerberos
  changed_when: true

- name: Enable samba server
  ansible.builtin.service:
    name: samba_server
    enabled: true
