- name: Configure samba
  ansible.builtin.template:
    src: smb4.conf.j2
    dest: /usr/local/etc/smb4.conf
    mode: '0600'
    owner: root
    group: wheel
    validate: '/usr/local/bin/testparm --suppress-prompt %s'

- name: Allow KDC to accept auth requests from samba with no PAC
  ansible.builtin.command: 'kadmin --local modify --attributes=no-auth-data-reqd cifs/cifs.{{ org_domain }}'
  delegate_to: kerberos
  changed_when: true

- name: Disable nmbd
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'nmbd_enable="NO"'

- name: Enable samba server
  ansible.builtin.service:
    name: samba_server
    enabled: true
