- name: Install samba port
  ansible.builtin.command: 'pkg install -y {{ setup_jail_cifs_samba_package }}'
  changed_when: true

- name: Configure samba
  ansible.builtin.template:
    src: smb4.conf.j2
    dest: /usr/local/etc/smb4.conf
    mode: '0644'
    owner: root
    group: wheel
    validate: '/usr/local/bin/testparm --suppress-prompt %s'

# TODO modify the cifs/cifs.empt.siva kerberos credential to avoid sending a
# PAC to samba with the 'no-auth-data-reqd' attribute

- name: Enable samba server
  ansible.builtin.service:
    name: samba_server
    enabled: true
