- name: Cleanup stale poudriere repos
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /usr/local/poudriere_repos/pkgbase
    - /usr/local/poudriere_repos/ports

- name: Create all missing directories on jailhost
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /usr/local/etc/pkg/repos
    - /usr/local/poudriere_repos/pkgbase
    - /usr/local/poudriere_repos/ports

- name: Copy poudriere repos to jailhost /tmp
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /tmp
    mode: '0600'
    owner: root
    group: wheel
  loop:
    - wyse-PoudrierePkgbase.tar.zst
    - wyse-PoudrierePorts.tar.zst

- name: Extract poudriere pkgbase repo
  ansible.builtin.command: tar -C /usr/local/poudriere_repos/pkgbase -xf /tmp/wyse-PoudrierePkgbase.tar.zst
  changed_when: true

- name: Extract poudriere ports repo
  ansible.builtin.command: tar -C /usr/local/poudriere_repos/ports -xf /tmp/wyse-PoudrierePorts.tar.zst
  changed_when: true

- name: Configure pkg to use Poudriere repo
  ansible.builtin.copy:
    content: |
      PoudrierePkgbase: {
        url: "file:///usr/local/poudriere_repos/pkgbase"
        enabled: yes
      }

      PoudrierePorts: {
        url: "file:///usr/local/poudriere_repos/ports"
        enabled: yes
      }

      FreeBSD: {
        url: "pkg+https://pkg.FreeBSD.org/${ABI}/latest",
        mirror_type: "srv",
        signature_type: "fingerprints",
        fingerprints: "/usr/share/keys/pkg",
        enabled: no
      }
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'

# NOTE See https://wiki.freebsd.org/PkgBase for .pkgsave fixes
- name: Upgrade whole system to new pkgbase while preserving passwd db
  ansible.builtin.shell: >
    pkg-static install -y -r PoudrierePkgbase -g 'FreeBSD-*' && {
      cp /etc/master.passwd.pkgsave /etc/master.passwd ;
      cp /etc/group.pkgsave /etc/group ;
      cp /etc/sysctl.conf.pkgsave /etc/sysctl.conf ;
      pwd_mkdb -p /etc/master.passwd
    }
  environment:
    # TODO don't hardcode this here
    ABI: "FreeBSD:15:amd64"
    IGNORE_OSVERSION: "yes"
  changed_when: true

- name: Reboot to new Pkgbase base system and (possibly) ABI
  ansible.builtin.reboot:

- name: Upgrade all ports on host system
  ansible.builtin.command: pkg upgrade -y -f -r PoudrierePorts
  changed_when: true

- name: Reboot to new ports userland
  ansible.builtin.reboot:
