- name: "Install useful testing and debug packages"
  ansible.builtin.command: 'pkg install -y tmux wget htop tree'
  changed_when: true

- name: "Configure tmux"
  ansible.builtin.copy:
    src: tmux.conf
    dest: '/home/{{ fresh_install_user }}/.tmux.conf'
    mode: '0644'
    owner: '{{ fresh_install_user }}'
    group: '{{ fresh_install_user }}'
