- name: Install nsd port from poudriere
  ansible.builtin.command: 'pkg install -y nsd'
  changed_when: true

- name: Configure nsd
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/nsd/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: templates/nsd/
  when: item.state == 'file'

- name: Enable nsd service
  ansible.builtin.lineinfile:
    path: '{{ jailroot }}/etc/rc.conf'
    line: 'nsd_enable=YES'
