- name: Install dns required ports
  ansible.builtin.command: pkg -r /empt/jails/dns install -y nsd
  delegate_to: jailhost
  changed_when: true

- name: Refresh ldconfig
  ansible.builtin.service:
    name: ldconfig
    state: started

- name: Configure nsd
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/nsd/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: templates/nsd/
  when: item.state == 'file'

- name: Enable nsd service
  ansible.builtin.service:
    name: nsd
    enabled: true
    state: started
