# TODO secure
secret_ca_passphrase: cakey

# TODO randomly generate the uids properly without collision
# currently hardcoding "randomly" for now
humans:
  - username: alice
    fullname: Alice Crypto
    uid: 4676
  - username: bob
    fullname: Bob Crypto
    uid: 11522
  - username: carol
    fullname: Carol Crypto
    uid: 23508
  - username: dan
    fullname: Dan Crypto
    uid: 39926
  - username: eve
    fullname: Eve Crypto
    uid: 7812
  - username: siva
    fullname: Siva Mahadevan
    uid: 5097

mailing_lists:
  - name: everyone
    recipients: '{{ humans | map(attribute="username") }}'
  - name: cryptoppl
    recipients:
      - alice
      - bob
      - carol
      - dan
      - eve
  - name: it
    recipients:
      - dan
      - eve

kerberos_service_principals:
  - service: cifs
    host: cifs
  - service: host
    host: ssh
  - service: imap
    host: mail
  - service: smtp
    host: mail
  - service: host
    host: irc
  # TODO should this be 'gunicorn'?
  - service: host
    host: radicale
