mailing_lists:
  - cryptoppl
  - everyone
  - helpdesk
  - it

# TODO randomly generate the uids properly without collision
# currently hardcoding "randomly" for now
humans:
  - username: alice
    fullname: Alice Crypto
    uid: 4676
    mailing_lists:
      - everyone
      - cryptoppl
  - username: bob
    fullname: Bob Crypto
    uid: 11522
    mailing_lists:
      - everyone
      - cryptoppl
  - username: carol
    fullname: Carol Crypto
    uid: 23508
    mailing_lists:
      - everyone
      - cryptoppl
  - username: dan
    fullname: Dan Crypto
    uid: 39926
    mailing_lists:
      - everyone
      - cryptoppl
      - it
  - username: eve
    fullname: Eve Crypto
    uid: 7812
    mailing_lists:
      - everyone
      - cryptoppl
      - it

kerberos_service_principals:
  - service: cifs
    host: cifs
  - service: imap
    host: mail
  - service: smtp
    host: mail
  - service: host
    host: irc
  - service: HTTP
    host: radicale

zrep_synced_dataset_properties:
  # TODO benchmark lz4 (default) vs zstd
  zroot/empt/synced/rw:
    exec: 'off'
    setuid: 'off'
    compression: zstd

# TODO secure
secret_ca_passphrase: cakey
certauth_cacrt_path: '/empt/synced/rw/{{ org_domain }}.cacrt.pem'
certauth_cakey_path: '/empt/synced/rw/{{ org_domain }}.cakey.pem'
