freebsd_version: 14.0-RELEASE
ula_subnet: '{{ ansible_host | ansible.utils.ipsubnet(64) }}'

# TODO secure
secret_ca_passphrase: cakey

# TODO determine if we should use DHCPv6 instead of random mac + SLAAC for each jail's IP
# TODO automate/loop the individual jail IP generation, especially the random_mac seeds
# TODO currently hardcoding the _random_ IPv6 addresses for convenience

host_jails_mapped_users:
  mlmmj:
    comment: Mlmmj Owner
    uid: 2000
    host_home_dir: /empt/email/mailing_lists
    guest_home_dir: /var/spool/mlmmj
  vmail:
    comment: Virtual Mail Handler
    uid: 2001
    host_home_dir: /empt/email/virtual_mail
    guest_home_dir: /var/mail/vhosts

special_zfs_datasets:
  - path: /empt/email/mailing_lists
    owner: mlmmj
  - path: /empt/email/virtual_attachments
    owner: vmail
  - path: /empt/email/virtual_mail
    owner: vmail

# TODO randomly generate the uids properly without collision
# currently hardcoding "randomly" for now
humans:
  - username: alice
    fullname: Alice Crypto
    uid: 4676
  - username: bob
    fullname: Bob Crypto
    uid: 11522
  - username: carol
    fullname: Carol Crypto
    uid: 23508
  - username: dan
    fullname: Dan Crypto
    uid: 39926
  - username: eve
    fullname: Eve Crypto
    uid: 7812
  - username: siva
    fullname: Siva Mahadevan
    uid: 5097

mailing_lists:
  - name: everyone
    recipients: '{{ humans | map(attribute="username") }}'
  - name: cryptoppl
    recipients:
      - alice
      - bob
      - carol
      - dan
      - eve

kerberos_service_principals:
  - service: cifs
    host: cifs
  - service: host
    host: ssh
  - service: imap
    host: mail
  - service: smtp
    host: mail
  - service: nfs
    host: jailhost
  - service: host
    host: irc
