mailing_lists:
  - cryptoppl
  - everyone
  - helpdesk
  - it

# TODO randomly generate the uids properly without collision
# currently hardcoding "randomly" for now
humans:
  - username: alice
    fullname: Alice Crypto
    uid: 4676
    mailing_lists:
      - everyone
      - cryptoppl
  - username: bob
    fullname: Bob Crypto
    uid: 11522
    mailing_lists:
      - everyone
      - cryptoppl
  - username: carol
    fullname: Carol Crypto
    uid: 23508
    mailing_lists:
      - everyone
      - cryptoppl
  - username: dan
    fullname: Dan Crypto
    uid: 39926
    mailing_lists:
      - everyone
      - cryptoppl
      - it
  - username: eve
    fullname: Eve Crypto
    uid: 7812
    mailing_lists:
      - everyone
      - cryptoppl
      - it
  - username: siva
    fullname: Siva Mahadevan
    uid: 5097
    mailing_lists:
      - everyone

kerberos_service_principals:
  - service: cifs
    host: cifs
  - service: imap
    host: mail
  - service: smtp
    host: mail
  - service: host
    host: irc
  - service: HTTP
    host: radicale

zrep_dataset_props:
  zroot/empt/etc:
    compression: zstd
  zroot/empt/helpdesk:
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/mail/postfix_spool:
    mountpoint: /empt/jails/mail/var/spool/postfix
  zroot/empt/jails/mail/mlmmj_spool:
    mountpoint: /empt/jails/mail/var/spool/mlmmj
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/kerberos/krb5data:
    mountpoint: /empt/jails/kerberos/var/heimdal
    exec: 'off'
    setuid: 'off'
  zroot/empt/jails/cifs/etc:
    compression: zstd
  zroot/empt/jails/cifs/logs:
    mountpoint: '/empt/jails/cifs/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/dns/etc:
    compression: zstd
  zroot/empt/jails/dns/logs:
    mountpoint: '/empt/jails/dns/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/irc/etc:
    compression: zstd
  zroot/empt/jails/irc/logs:
    mountpoint: '/empt/jails/irc/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/kerberos/etc:
    compression: zstd
  zroot/empt/jails/kerberos/logs:
    mountpoint: '/empt/jails/kerberos/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/mail/etc:
    compression: zstd
  zroot/empt/jails/mail/logs:
    mountpoint: '/empt/jails/mail/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd
  zroot/empt/jails/radicale/etc:
    compression: zstd
  zroot/empt/jails/radicale/logs:
    mountpoint: '/empt/jails/radicale/var/log'
    exec: 'off'
    setuid: 'off'
    compression: zstd

# TODO secure
secret_ca_passphrase: cakey
certauth_cacrt_path: '/empt/etc/{{ org_domain }}.cacrt.pem'
certauth_cakey_path: '/empt/etc/{{ org_domain }}.cakey.pem'
