freebsd_version: 13.2-RELEASE
ula_subnet: '{{ hostvars["jailhost"].ansible_host | ansible.utils.ipsubnet(64) }}'

# TODO secure
secret_ca_passphrase: cakey

# TODO determine if we should use DHCPv6 instead of random mac + SLAAC for each jail's IP
# TODO automate/loop the individual jail IP generation, especially the random_mac seeds
# TODO currently hardcoding the _random_ IPv6 addresses for convenience

host_jails_mapped_users:
  mlmmj:
    comment: Mlmmj Owner
    uid: 2000
    host_home_dir: /empt/email/mailing_lists
    guest_home_dir: /var/spool/mlmmj
  vmail:
    comment: Virtual Mail Handler
    uid: 2001
    host_home_dir: /empt/email/virtual_mail
    guest_home_dir: /var/mail/vhosts

special_zfs_datasets:
  - path: /empt/email/mailing_lists
    owner: mlmmj
  - path: /empt/email/virtual_attachments
    owner: vmail
  - path: /empt/email/virtual_mail
    owner: vmail

humans:
  - username: alice
    fullname: Alice Crypto
    uid: '{{ 60000 | random(start=3000) }}'
  - username: bob
    fullname: Bob Crypto
    uid: '{{ 60000 | random(start=3000) }}'
  - username: carol
    fullname: Carol Crypto
    uid: '{{ 60000 | random(start=3000) }}'
  - username: dan
    fullname: Dan Crypto
    uid: '{{ 60000 | random(start=3000) }}'
  - username: eve
    fullname: Eve Crypto
    uid: '{{ 60000 | random(start=3000) }}'

mailing_lists:
  - name: everyone
    recipients: '{{ humans | map(attribute="username") }}'
  - name: cryptoppl
    recipients:
      - alice
      - bob
      - carol
      - dan
      - eve

kerberos_service_principals:
  - service: cifs
    host: cifs
    keytab_dest: /empt/jails/cifs/etc/krb5.keytab
  - service: host
    host: ssh
    keytab_dest: /empt/jails/ssh/etc/krb5.keytab
  - service: imap
    host: mail
    keytab_dest: /empt/jails/mail/etc/krb5.keytab
  - service: smtp
    host: mail
    keytab_dest: /empt/jails/mail/etc/krb5.keytab
  - service: nfs
    host: jailhost
    keytab_dest: /etc/krb5.keytab
