freebsd_version: 13.2-RELEASE
ula_subnet: '{{ hostvars["jailhost.empt.siva"].ansible_host | ansible.utils.ipsubnet(64) }}'

# TODO secure
secret_ca_passphrase: cakey

# TODO determine if we should use DHCPv6 instead of random mac + SLAAC for each jail's IP
# TODO automate/loop the individual jail IP generation, especially the random_mac seeds
# TODO currently hardcoding the _random_ IPv6 addresses for convenience
