# Currently needed for bootstrapping domain information before ansible fact
# gathering works on jails. Technically this isn't needed, since we can do all
# jailhost setup after the jails' facts have been gathered. However, this makes
# it much easier to track, and doesn't accidentally run into other local FQDN
# names like '.lan'.
# TODO see if there's a cleaner way to do this centrally, or automatically
# through fact gathering.
org_domain: empt.siva

freebsd_version: 13.2-RELEASE
ula_subnet: '{{ hostvars["jailhost"].ansible_host | ansible.utils.ipsubnet(64) }}'

# TODO secure
secret_ca_passphrase: cakey

# TODO determine if we should use DHCPv6 instead of random mac + SLAAC for each jail's IP
# TODO automate/loop the individual jail IP generation, especially the random_mac seeds
# TODO currently hardcoding the _random_ IPv6 addresses for convenience

host_jails_mapped_users:
  mlmmj:
    comment: Mlmmj Owner
    uid: 2000
    host_home_dir: /empt/email/mailing_lists
    guest_home_dir: /var/spool/mlmmj
  vmail:
    comment: Virtual Mail Handler
    uid: 2001
    host_home_dir: /empt/email/virtual_mail
    guest_home_dir: /var/mail/vhosts

special_zfs_datasets:
  - path: /empt/email/mailing_lists
    owner: mlmmj
  - path: /empt/email/virtual_attachments
    owner: vmail
  - path: /empt/email/virtual_mail
    owner: vmail

# TODO random UID generation
humans:
  alice:
    fullname: Alice Crypto
    uid: 3000
  bob:
    fullname: Bob Crypto
    uid: 3001
  carol:
    fullname: Carol Crypto
    uid: 3002
  dan:
    fullname: Dan Crypto
    uid: 3003
  eve:
    fullname: Eve Crypto
    uid: 3004
  siva:
    fullname: Siva Mahadevan
    uid: 3005

mailing_lists:
  everyone:
    recipients: '{{ humans.keys() | list }}'
  cryptoppl:
    recipients:
      - alice
      - bob
      - carol
      - dan
      - eve

kerberos_service_principals:
  - service: host
    host: ssh
  - service: imap
    host: mail
  - service: smtp
    host: mail
      #- service: cifs
      #  host: cifs
