# TODO turn this into a FreeBSD ports pkg
# =======================================
- name: Copy helpdesk triage script to etc dataset
  ansible.builtin.template:
    src: helpdesk.sh.j2
    dest: /empt/synced/bin/helpdesk.sh
    mode: '0700'
    owner: root
    group: wheel

- name: Install EMPT administration task scripts to etc dataset
  ansible.builtin.copy:
    src: tasks
    dest: /empt/synced/bin/
    mode: '0700'
    owner: root
    group: wheel
# =======================================

- name: Create system account for the empthelper helpdesk agent
  ansible.builtin.user:
    name: empthelper
    comment: EMPT Helpdesk Agent
    home: /empt/synced/rw/helpdesk
    create_home: false
    shell: /usr/sbin/nologin
# TODO find a way to create a globally unique UID, currently hardcoding
    uid: 21891
  register: setup_jail_empthelper_user

- name: Create directory layout under helpdesk dataset
  ansible.builtin.file:
    name: '/empt/synced/rw/helpdesk/{{ item }}'
    state: directory
    mode: '0700'
    owner: empthelper
    group: empthelper
  loop:
    - mail/cur
    - mail/new
    - mail/tmp

- name: Add empthelper maildir directory nullfs mount to mail jail
  ansible.posix.mount:
    fstab: /empt/synced/rw/fstab.d/mail.fstab
    src: /empt/synced/rw/helpdesk/mail
    path: /empt/jails/mail/home/empthelper/mail
    fstype: nullfs
    opts: rw
    state: mounted

- name: Create empthelper mail delivery local account in the mail jail
  ansible.builtin.user:
    name: '{{ setup_jail_empthelper_user.name }}'
    comment: '{{ setup_jail_empthelper_user.comment }}'
    shell: /usr/sbin/nologin
    home: '/home/{{ setup_jail_empthelper_user.name }}'
    create_home: false
    uid: '{{ setup_jail_empthelper_user.uid }}'
  delegate_to: mail

- name: Silently subscribe the helpdesk and IT staff to the helpdesk mailing list
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/helpdesk -a {{ item }}@{{ org_domain }} -fqs'
  loop:
    - it
    - empthelper
  delegate_to: mail
  register: setup_jail_helpdesk_mlmmj_sub_output
  changed_when: setup_jail_helpdesk_mlmmj_sub_output.rc == 0

- name: Install fdm configuration
  ansible.builtin.template:
    src: fdm.conf.j2
    dest: /empt/synced/rw/helpdesk/.fdm.conf
    mode: '0600'
    owner: empthelper
    group: empthelper
    validate: fdm -f %s -n

- name: Allow the empthelper to only run the helpdesk triage script
  ansible.builtin.lineinfile:
    path: /usr/local/etc/doas.conf
    line: 'permit nopass setenv { HELPDESK_FROM HELPDESK_CC HELPDESK_MESSAGE_ID HELPDESK_SUBJECT HELPDESK_REFERENCES } empthelper cmd /empt/synced/bin/helpdesk.sh args'
    create: true
    mode: '0600'
    owner: root
    group: wheel

- name: Enable cronjob to periodically process helpdesk queue with fdm
  ansible.builtin.cron:
    user: empthelper
    name: process helpdesk queue with fdm
    job: -n -q fdm -a helpdesk -l fetch
