- name: Create system account for the empthelper helpdesk agent
  ansible.builtin.user:
    name: empthelper
    comment: EMPT Helpdesk Agent
    home: /empt/synced/helpdesk
    create_home: false
    shell: /usr/sbin/nologin
# TODO find a way to create a globally unique UID, currently hardcoding
    uid: 21891
  register: setup_jail_empthelper_user

# TODO turn these scripts into a FreeBSD ports pkg
# =======================================
- name: Copy helpdesk scripts to synced bin
  ansible.builtin.copy:
    src: helpdesk
    dest: /empt/synced/
    mode: '0700'
    owner: empthelper
    group: empthelper
# =======================================

- name: Create maildir layout under helpdesk dataset
  ansible.builtin.file:
    name: '/empt/synced/helpdesk/mail/{{ item }}'
    state: directory
    mode: '0700'
    owner: empthelper
    group: empthelper
  loop:
    - cur
    - new
    - tmp

- name: Add empthelper maildir directory nullfs mount to mail jail
  ansible.posix.mount:
    fstab: /empt/synced/rw/fstab.d/mail.fstab
    src: /empt/synced/helpdesk/mail
    path: /empt/jails/mail/home/empthelper/mail
    fstype: nullfs
    opts: rw
    state: mounted

- name: Create empthelper mail delivery local account in the mail jail
  ansible.builtin.user:
    name: empthelper
    comment: EMPT Helpdesk Agent
    shell: /usr/sbin/nologin
    home: /home/empthelper
    create_home: false
    uid: '{{ setup_jail_empthelper_user.uid }}'
  delegate_to: mail

- name: Silently subscribe the helpdesk and IT staff to the helpdesk mailing list
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/helpdesk -a {{ item }}@{{ org_domain }} -fqs'
  loop:
    - it
    - empthelper
  delegate_to: mail
  register: setup_jail_helpdesk_mlmmj_sub_output
  changed_when: setup_jail_helpdesk_mlmmj_sub_output.rc == 0

- name: Install fdm configuration
  ansible.builtin.template:
    src: fdm.conf.j2
    dest: /empt/synced/helpdesk/.fdm.conf
    mode: '0600'
    owner: empthelper
    group: empthelper
    validate: fdm -f %s -n

- name: Allow the empthelper to only run helpdesk task scripts
  ansible.builtin.lineinfile:
    path: /usr/local/etc/doas.conf
    line: 'permit nopass keepenv empthelper cmd /empt/synced/helpdesk/tasks/{{ item }}.sh'
    create: true
    mode: '0600'
    owner: root
    group: wheel
  # TODO generate the loop from the files inside the tasks folder
  loop:
    - groups

- name: Enable cronjob to periodically process helpdesk queue with fdm
  ansible.builtin.cron:
    user: empthelper
    name: process helpdesk queue with fdm
    job: -n -q fdm -a helpdesk fetch
