- name: Install ansible CA crypto dependencies
  ansible.builtin.command: 'pkg install -y py311-cryptography'
  changed_when: true

# TODO waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1325335 for ED25519 support
# generating P-256 keys in the meantime
# TODO passphrase
- name: Create private key for new host certificate on each jail
  community.crypto.openssl_privatekey:
    path: '{{ gen_host_cert_key_path }}'
    backup: true
    type: ECC
    curve: secp256r1

- name: Create CSR for new server certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: '{{ gen_host_cert_key_path }}'
    common_name: '{{ inventory_hostname }}.{{ org_domain }}'
  register: gen_host_cert_csr

- name: Check whether certificate already exists
  ansible.builtin.stat:
    path: '{{ gen_host_cert_crt_path }}'
  register: gen_host_cert_certificate_exists

- name: Read existing certificate if exists
  ansible.builtin.slurp:
    src: '{{ gen_host_cert_crt_path }}'
  when: gen_host_cert_certificate_exists.stat.exists
  register: gen_host_cert_certificate

- name: Sign certificate with the CA
  community.crypto.x509_certificate_pipe:
    content: '{{ (gen_host_cert_certificate.content | b64decode) if gen_host_cert_certificate_exists.stat.exists else omit }}'
    csr_content: '{{ gen_host_cert_csr.csr }}'
    provider: ownca
    ownca_path: '{{ certauth_cacrt_path }}'
    ownca_privatekey_path: '{{ certauth_cakey_path }}'
    ownca_privatekey_passphrase: '{{ secret_ca_passphrase }}'
    ownca_not_after: '+365d'  # valid for one year
    ownca_not_before: '-1d'  # valid since yesterday
  delegate_to: jailhost
  register: gen_host_cert_certificate
  notify:
    - Write new host certificate file
