- name: Activate fresh install FreeBSD boot environment
  ansible.builtin.command: bectl activate default
  changed_when: true

- name: Reboot to fresh boot environment
  ansible.builtin.reboot:

- name: Destroy EMPT installation boot environment
  ansible.builtin.command: bectl destroy empt_fresh
  changed_when: true
  failed_when: false

- name: Destroy EMPT ZFS datasets
  ansible.builtin.command: zfs destroy -Rf zroot/empt
  changed_when: true
  failed_when: false
