- name: Install required packages from poudriere
  ansible.builtin.command: 'pkg install -r {{ jailroot }} -y postfix dovecot mlmmj'

- name: Configure postfix
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ jailroot }}/usr/local/etc/postfix/{{ item.path | replace(".j2", "")}}'
    mode: '0644'
  with_filetree: 'postfix/'
  when: item.state == 'file'

- name: Configure dovecot
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ jailroot }}/usr/local/etc/dovecot/{{ item.path | replace(".j2", "")}}'
    mode: '0644'
  with_filetree: 'dovecot/'
  when: item.state == 'file'
