- name: Write new host certificate file
  ansible.builtin.copy:
    dest: '{{ crt_path }}'
    content: '{{ gen_host_cert_certificate.certificate }}'
    owner: root
    group: wheel
    mode: '0644'
