- name: Create system account for cron monitoring tasks in the jail
  ansible.builtin.user:
    name: cronmonitor
    comment: Cron Monitor
    shell: /usr/sbin/nologin
    generate_ssh_key: true
    ssh_key_type: ed25519
  register: setup_jail_cronmonitor_jail_user

- name: Create system account for receiving monitoring comamnds in the jailhost
  ansible.builtin.user:
    name: monitoragent
    comment: Monitor Agent
  delegate_to: jailhost

- name: Authorize cronmonitor ssh key on jailhost for receiving monitoring commands
  ansible.posix.authorized_key:
    user: monitoragent
    key: '{{ setup_jail_cronmonitor_jail_user.ssh_public_key }}'
  delegate_to: jailhost

- name: Retrieve jailhost ssh host public key
  ansible.builtin.command: ssh-keyscan -t ed25519 jailhost
  changed_when: false
  register: setup_jail_cronmonitor_jailhost_host_pubkeys

- name: Add jailhost ssh host public keys to known_hosts
  ansible.builtin.known_hosts:
    name: jailhost
    key: '{{ item }}'
    path: /home/cronmonitor/.ssh/known_hosts
  loop: '{{ setup_jail_cronmonitor_jailhost_host_pubkeys.stdout_lines | flatten(levels=1) }}'

- name: Install dma mailer configuration
  ansible.builtin.template:
    src: dma/dma.conf.j2
    dest: /etc/dma/dma.conf
    mode: '0644'
    owner: root
    group: wheel

# TODO move this into a reusable role/template
# =========
- name: Set crontab MAILTO
  ansible.builtin.cron:
    name: MAILTO
    user: cronmonitor
    env: true
    job: 'it@{{ org_domain }}'

- name: Setup crontab with useful checks
  ansible.builtin.cron:
    name: check cpu usage
    user: cronmonitor
    job: >
      ssh monitoragent@jailhost
      '/usr/local/libexec/nagios/check_load -r -w 0.75 -c 0.95 | /usr/bin/grep -E "^(WARNING|CRITICAL)"'
# =========
