# Expects variable:
# human:
#   username: "str"
#   fullname: "str"

- name: Create storage dataset for human
  community.general.zfs:
    name: 'zroot/empt/human_storage/{{ human.username }}'
    state: present
    extra_zfs_properties:
      canmount: 'on'
      quota: '1G'
      reservation: '1G'

- name: Set owner and group permissions for the new storage dataset
  ansible.builtin.file:
    name: '/empt/human_storage/{{ human.username }}'
    state: directory
    mode: '1700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'

- name: Populate human-owned storage directories
  ansible.builtin.file:
    name: '/empt/human_storage/{{ human.username }}/{{ item }}'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'
  loop:
    - home
    - mail/cur
    - mail/new
    - mail/tmp

- name: Query radicale UNIX system account UID
  ansible.builtin.user:
    name: radicale
  delegate_to: radicale
  register: new_human_radicale_system_account

- name: Populate human calendar/contacts directories
  ansible.builtin.file:
    name: '/empt/human_storage/{{ human.username }}/diary/{{ item }}'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ new_human_radicale_system_account.uid }}'
    group: '{{ new_human_radicale_system_account.uid }}'
  loop:
    - calendar
    - contacts
    - journal
    - todo

- name: Initialize radicale properties for each new collection
  ansible.builtin.template:
    src: 'radicale/{{ item }}/Radicale.props.json.j2'
    dest: '/empt/human_storage/{{ human.username }}/diary/{{ item }}/.Radicale.props'
    mode: '0600'
    owner: '{{ new_human_radicale_system_account.uid }}'
    group: '{{ new_human_radicale_system_account.uid }}'
  loop:
    - calendar
    - contacts
    - journal
    - todo

- name: Create login-incapable unix accounts for the human in the required hosts
  ansible.builtin.user:
    name: '{{ human.username }}'
    comment: '{{ human.fullname }}'
    home: '/home/{{ human.username }}'
    create_home: false
    uid: '{{ human.uid }}'
    shell: /usr/sbin/nologin
  delegate_to: '{{ item }}'
  loop:
    # TODO do I need cifs here?
    - cifs
    - mail

- name: Create missing nullfs mountpoint for the home directory in cifs
  ansible.builtin.file:
    name: '/home/{{ human.username }}'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'
  delegate_to: cifs

- name: Create missing nullfs mountpoint for Maildir
  ansible.builtin.file:
    name: '/home/{{ human.username }}/mail'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'
  delegate_to: mail

# TODO can we change wsgi-kerberos to return REMOTE_USER=<username> instead of
# REMOTE_USER=<username>@<REALM>?
- name: Create missing nullfs mountpoint for radicale collections
  ansible.builtin.file:
    name: '/usr/local/share/radicale/collection-root/{{ human.username }}@{{ org_domain | upper }}'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ new_human_radicale_system_account.uid }}'
    group: '{{ new_human_radicale_system_account.uid }}'
  delegate_to: radicale

- name: Add human home directory nullfs mount to cifs jail
  ansible.builtin.lineinfile:
    path: /empt/etc/cifs/fstab
    line: '/empt/human_storage/{{ human.username }}/home /empt/jails/cifs/home/{{ human.username }} nullfs rw 0 0'

- name: Add Maildir nullfs mount to mail jail
  ansible.builtin.lineinfile:
    path: /empt/etc/mail/fstab
    line: '/empt/human_storage/{{ human.username }}/mail /empt/jails/mail/home/{{ human.username }}/mail nullfs rw 0 0'

- name: Add diary collections nullfs mount to radicale jail
  ansible.builtin.lineinfile:
    path: /empt/etc/radicale/fstab
    line: '/empt/human_storage/{{ human.username }}/diary /empt/jails/radicale/usr/local/share/radicale/collection-root/{{ human.username }}@{{ org_domain | upper }} nullfs rw 0 0'

# TODO actually mount all these directories

# TODO a lot of bugs with Heimdal's `get` and `list` commands, fix them.
- name: Check which user principals are missing
  ansible.builtin.command: '/usr/local/bin/kadmin --local get --short {{ human.username }}'
  delegate_to: kerberos
  register: new_human_user_principal_exists
  failed_when: new_human_user_principal_exists.rc >= 2
  changed_when: false

- name: Add new kerberos principal
  ansible.builtin.command: '/usr/local/bin/kadmin --local add --password={{ human.username }} --use-defaults {{ human.username }}'
  delegate_to: kerberos
  when: '"Principal does not exist" in new_human_user_principal_exists.stderr'
  register: setup_jail_kerberos_add_user_principals_output
  changed_when: setup_jail_kerberos_add_user_principals_output.rc == 0

- name: Subscribe to full organization mailing list
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/everyone -a {{ human.username }}@{{ org_domain }} -c -f -s'
  delegate_to: mail
  register: mlmmj_sub_output
  changed_when: mlmmj_sub_output.rc == 0
