# Expects variable:
# human:
#   username: "str"
#   fullname: "str"

- name: "Create empt home directory in jailhost"
  community.general.zfs:
    name: 'zroot/empt/homes/{{ human.username }}'
    state: present
    extra_zfs_properties:
      canmount: 'on'
      quota: '1G'
      reservation: '1G'

- name: Create empty Maildir for the human
  ansible.builtin.file:
    name: '/empt/homes/{{ human.username }}/Mail/{{ item }}'
    state: directory
    recurse: true
    mode: '0700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'
  loop:
    - cur
    - new
    - tmp

- name: "Change ownership of home strictly narrowed down to human"
  ansible.builtin.file:
    name: '/empt/homes/{{ human.username }}'
    state: directory
    recurse: true
    mode: '1700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'

- name: "Create login-incapable system unix users in the required hosts"
  ansible.builtin.user:
    name: '{{ human.username }}'
    comment: '{{ human.fullname }}'
    home: '/home/{{ human.username }}'
    create_home: false
    uid: '{{ human.uid }}'
    shell: /usr/sbin/nologin
  delegate_to: '{{ item }}'
  loop:
    - cifs
    - mail

- name: "Create a login-capable unix user for the human in the ssh jail"
  ansible.builtin.user:
    name: '{{ human.username }}'
    comment: '{{ human.fullname }}'
    home: '/home/{{ human.username }}'
    create_home: false
    uid: '{{ human.uid }}'
  delegate_to: ssh

- name: "Add new home directory nullfs mount to dependent service jail fstabs"
  ansible.builtin.lineinfile:
    path: '/empt/etc/jail_fstabs/{{ item }}.fstab'
    line: '/empt/homes/{{ human.username }} /empt/jails/{{ item }}/home/{{ human.username }} nullfs rw 0 0'
  loop:
    - cifs
    - ssh

- name: Add Maildir nullfs mount to mail jail
  ansible.builtin.lineinfile:
    path: /empt/etc/jail_fstabs/mail.fstab
    line: '/empt/homes/{{ human.username }}/Mail /empt/jails/mail/home/{{ human.username }}/Mail nullfs rw 0 0'

- name: Create missing nullfs mountpoint for user home directories in corresponding jails
  ansible.builtin.file:
    name: '/empt/jails/{{ item }}/home/{{ human.username }}'
    state: directory
    recurse: true
    mode: '0700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'
  loop:
    - cifs
    - ssh

- name: Create missing nullfs mountpoint for Maildir
  ansible.builtin.file:
    name: '/empt/jails/mail/home/{{ human.username }}/Mail'
    state: directory
    recurse: true
    mode: '0700'
    owner: '{{ human.uid }}'
    group: '{{ human.uid }}'

# TODO a lot of bugs with Heimdal's `get` and `list` commands, fix them.
- name: "Check which user principals are missing"
  ansible.builtin.command: '/usr/local/bin/kadmin --local get --short {{ human.username }}'
  delegate_to: kerberos
  register: new_human_user_principal_exists
  failed_when: new_human_user_principal_exists.rc >= 2
  changed_when: false

- name: "Add new kerberos principal"
  ansible.builtin.command: '/usr/local/bin/kadmin --local add --password={{ human.username }} --use-defaults {{ human.username }}'
  delegate_to: kerberos
  when: '"Principal does not exist" in new_human_user_principal_exists.stderr'
  register: setup_jail_kerberos_add_user_principals_output
  changed_when: setup_jail_kerberos_add_user_principals_output.rc == 0

- name: "Subscribe to full organization mailing list"
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/{{ org_domain }}/everyone -a {{ human.username }}@{{ org_domain }} -c -f -s'
  delegate_to: mail
  register: mlmmj_sub_output
  changed_when: mlmmj_sub_output.rc == 0
