---
- name: Setup ssh mutual trust between primary and secondary
  hosts: localhost
  vars_files:
    - vars/shared.yml
  roles:
    - zrep_setup_mutual_trust

- name: Setup zrep system users on both primary and secondary
  hosts: jailhosts
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Create zrep system user for crontab
      ansible.builtin.user:
        name: zrep
        comment: Zrep Cron Agent
        home: /nonexistent
        create_home: false
        shell: /usr/sbin/nologin

- name: Initialize all zrep backed up datasets
  hosts: localhost
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Initialize zrep state on all datasets to be backed up
      ansible.builtin.include_role:
        name: zrep_init_dataset
      loop: '{{ zrep_dataset_props | dict2items }}'
      loop_control:
        loop_var: zrep_init_dataset_dataset

- name: Unmount entire zroot/empt parent dataset on secondary
  hosts: jailhost-secondary
  tasks:
    - name: Unmount zroot/empt
      ansible.builtin.command: zfs unmount zroot/empt
      register: activate_zrep_empt_unmount
      failed_when: activate_zrep_empt_unmount.rc != 0 and "not currently mounted" not in activate_zrep_empt_unmount.stderr
      changed_when: true
