---
- name: Start a fresh EMPT installation
  hosts: jailhosts
  roles:
    - factory_reset
    - create_boot_environment

# NOTE Needs to 'become' root with 'su' to avoid
# /etc/master.passwd pkgbase troubles
    - update_poudriere

    - bootstrap

- name: Install ansible with dependencies and copy EMPT ansible setup
  hosts: jailhosts
  tasks:
    - name: Install ansible and its dependencies
      ansible.builtin.command: pkg install -y py311-ansible py311-cryptography py311-netaddr rsync
      changed_when: true

    - name: Copy EMPT ansible setup directory to tmp
      ansible.posix.synchronize:
        src: .
        dest: /tmp/empt-ansible
