---
- name: Bootstrap jailhost
  hosts: jailhost
  remote_user: siva
  become: true
  become_method: ansible.builtin.su
  gather_facts: false
  roles:
    - bootstrap

- name: Setup jailhost
  hosts: jailhost
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - update_poudriere
    - setup_jailhost
      # TODO remove once everything is ready for production
    - setup_siva_debug

- name: Bootstrap all jails
  hosts: jails
  remote_user: root
  gather_facts: false
  roles:
    - bootstrap

- name: Refresh /etc/hosts for each host in the inventory
  hosts: all
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - refresh_etc_hosts

- name: Setup certauth jail
  hosts: certauth
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: false
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_certauth

- name: Generate host certs for each jail
  hosts: jails
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: false
  vars_files:
    - vars/shared.yml
  roles:
    - gen_host_cert

- name: Setup kerberos KDC
  hosts: kerberos
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: false
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_kerberos

- name: Move all keytabs to their respective hosts
  hosts: jailhost
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: false
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Copy keytab from jailhost to jail
      ansible.builtin.copy:
        src: '/jails/kerberos/tmp/{{ hostvars[item.host].ansible_fqdn }}.keytab'
        remote_src: true
        dest: '/jails/{{ item.host }}/etc/krb5.keytab'
        mode: '0600'
        owner: root
        group: wheel
      tags: always
      loop: '{{ kerberos_service_principals }}'

- name: Setup mail server jail
  hosts: mail
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_mail

- name: Create all pre-configured mlmmj mailing lists inside mail server jail
  hosts: mail
  remote_user: mlmmj
  gather_facts: false
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Create mlmmj mailing list
      ansible.builtin.include_tasks: mlmmj_make_ml.yml
      loop: '{{ mailing_lists }}'
      loop_control:
        loop_var: setup_jail_mail_mailinglist
