---

- name: Bootstrap all ansible prereqs onto freshly installed FreeBSD host
  hosts: all
  become: true
  become_method: su
  gather_facts: false
  roles:
    - bootstrap

- name: Run all playbook roles
  hosts: all
  become: true
  become_method: doas
  gather_facts: true
  roles:
    - all_jails

#- name: Setup jail_dns
#  hosts: jail_dns
