---
- name: Bootstrap jailhost
  hosts: jailhost.empt.siva
  remote_user: siva
  become: true
  become_method: ansible.builtin.su
  gather_facts: false
  roles:
    - bootstrap

- name: Setup jailhost
  hosts: jailhost.empt.siva
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - update_poudriere
    - setup_jailhost

- name: Bootstrap all jails
  hosts: jails
  remote_user: root
  become: false
  gather_facts: false
  roles:
    - bootstrap

- name: Setup certauth jail
  hosts: certauth.empt.siva
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_certauth

- name: Generate host certs for each jail
  hosts: jails
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - gen_host_cert

# - name: Final cleanup
#   hosts: jailhost.empt.siva
#   remote_user: ansible
#   become: true
#   become_method: community.general.doas
#   gather_facts: false
#   tasks:
#     - name: Stop all jails
#       ansible.builtin.service:
#         name: jail
#         state: stopped
