---
- name: Bootstrap jailhost
  hosts: cl100
  remote_user: siva
  become: true
  become_method: su
  gather_facts: false
  roles:
    - bootstrap

- name: Setup jailhost
  hosts: cl100
  remote_user: ansible
  become: true
  become_method: doas
  gather_facts: true
  vars_files:
    - vars/shared.yml
  roles:
    - update_poudriere
    - setup_jailhost

- name: Bootstrap all jails
  hosts:
    # - jail_certauth
    # - jail_dns
    # - jail_kerberos
    - jail_logs
    # - jail_mail
    # - jail_prometheus
    # - jail_ssh
  remote_user: root
  become: false
  gather_facts: false
  roles:
    - bootstrap

- name: Setup logs jail
  hosts: jail_logs
  remote_user: ansible
  become: true
  become_method: doas
  gather_facts: true
  vars:
    jail: '{{ jail_logs }}'
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_logs

# - name: Final cleanup
#   hosts: cl100
#   remote_user: ansible
#   become: true
#   become_method: doas
#   gather_facts: false
#   tasks:
#     - name: Stop all jails
#       ansible.builtin.service:
#         name: jail
#         state: stopped
