---
- name: Bootstrap jailhost
  hosts: 'jailhost.{{ org_domain }}'
  remote_user: '{{ fresh_install_user }}'
  become: true
  become_method: ansible.builtin.su
  roles:
    - bootstrap

- name: Setup jailhost
  hosts: 'jailhost.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - update_poudriere

      # TODO remove once everything is ready for production
    - setup_convenience_tools

    - setup_jailhost

- name: Bootstrap all jails
  hosts: jails
  strategy: free
  remote_user: root
  roles:
    - bootstrap

#- name: Reboot to refresh hostnames and FQDNs
#  hosts: 'jailhost.{{ org_domain }}'
#  remote_user: ansible
#  become: true
#  become_method: community.general.doas
#  tasks:
#    - name: Reboot
#      ansible.builtin.reboot:
#        # TODO there must be a cleaner way of doing this, but for now, this works
#        # NOTE this checks that ALL jails are active by checking the *number* of active jails
#        # against our known number
#        test_command: 'jls name | wc -l | xargs test {{ groups["jails"] | count }} ='

- name: Refresh /etc/hosts on all hosts
  hosts: all
  remote_user: ansible
  become: true
  become_method: community.general.doas
  roles:
    - refresh_etc_hosts

- name: Setup certauth jail
  hosts: 'certauth.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  environment:
    CRYPTOGRAPHY_OPENSSL_NO_LEGACY: 1
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_certauth

- name: Generate host certs for each jail
  hosts: jails
  strategy: free
  remote_user: ansible
  become: true
  become_method: community.general.doas
  environment:
    CRYPTOGRAPHY_OPENSSL_NO_LEGACY: 1
  vars_files:
    - vars/shared.yml
  roles:
    - gen_host_cert

- name: Setup kerberos KDC
  hosts: 'kerberos.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_kerberos

- name: Setup IRC jail
  hosts: 'irc.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_irc

- name: Setup DNS server jail
  hosts: 'dns.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_dns

- name: Setup samba CIFS jail
  hosts: 'cifs.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_cifs

- name: Setup ssh jail
  hosts: 'ssh.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_ssh

- name: Setup mail server jail
  hosts: 'mail.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_mail

- name: Create all pre-configured mailing lists
  hosts: 'mail.{{ org_domain }}'
  remote_user: mlmmj
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Create mailing list
      ansible.builtin.include_tasks: mlmmj_make_ml.yml
      loop: '{{ mailing_lists }}'
      loop_control:
        loop_var: mailing_list

- name: Add all pre-configured humans
  hosts: 'jailhost.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Add human
      ansible.builtin.include_role:
        name: new_human
      loop: '{{ humans }}'
      loop_control:
        loop_var: human

- name: Reboot after successful run
  hosts: 'jailhost.{{ org_domain }}'
  remote_user: ansible
  become: true
  become_method: community.general.doas
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
