---
- name: Setup jailhost
  hosts: jailhost
  vars_files:
    - vars/shared.yml
  roles:
      # TODO remove once everything is ready for production
    - setup_convenience_tools
    - setup_jailhost
  tasks:
    # TODO file bug for service module not working here
    - name: Start all jails
      ansible.builtin.command: service jail onerestart # noqa: command-instead-of-module
      changed_when: true

- name: Refresh /etc/hosts in all jails
  hosts: jails
  roles:
    - refresh_etc_hosts

# TODO organize this better maybe
- name: Setup TLS private certificate authority
  hosts: jailhost
  environment:
    CRYPTOGRAPHY_OPENSSL_NO_LEGACY: "1"
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Create locally trusted CA certs directory
      ansible.builtin.file:
        path: /usr/local/etc/ssl/certs
        state: directory
        mode: '0755'
        owner: root
        group: wheel

    # TODO waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1325335 for ED25519 support
    # generating P-256 keys in the meantime
    - name: Create CA private key with password protection
      community.crypto.openssl_privatekey:
        path: '{{ certauth_cakey_path }}'
        passphrase: "{{ secret_ca_passphrase }}"
        type: ECC
        curve: secp256r1
        cipher: auto

    - name: Create CSR for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: '{{ certauth_cakey_path }}'
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        common_name: '{{ org_domain }} CA'
        use_common_name_for_san: false # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: certauth_ca_csr

    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: '{{ certauth_cacrt_path }}'
        csr_content: "{{ certauth_ca_csr.csr }}"
        privatekey_path: '{{ certauth_cakey_path }}'
        privatekey_passphrase: "{{ secret_ca_passphrase }}"
        provider: selfsigned

    - name: Rehash trusted certs on system
      ansible.builtin.command: certctl rehash
      changed_when: true

- name: Generate host certs for each jail
  hosts: jails
  environment:
    CRYPTOGRAPHY_OPENSSL_NO_LEGACY: "1"
  vars_files:
    - vars/shared.yml
  roles:
    - gen_host_cert

- name: Setup kerberos KDC
  hosts: kerberos
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_kerberos

- name: Setup IRC jail
  hosts: irc
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_irc

- name: Setup DNS server jail
  hosts: dns
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_dns

- name: Setup samba CIFS jail
  hosts: cifs
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_cifs

- name: Setup mail server jail
  hosts: mail
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_mail

- name: Setup radicale jail
  hosts: radicale
  vars_files:
    - vars/shared.yml
  roles:
    - setup_jail_radicale

- name: Create all pre-configured mailing lists
  hosts: mail
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Create mailing list
      ansible.builtin.include_role:
        name: mlmmj_make_ml
      loop: '{{ mailing_lists }}'
      loop_control:
        loop_var: mailing_list

- name: Open the helpdesk for business
  hosts: jailhost
  vars_files:
    - vars/shared.yml
  roles:
    - open_jailhost_helpdesk

- name: Start the cron monitor
  hosts: jailhost
  vars_files:
    - vars/shared.yml
  roles:
    - start_cronmonitor
