# Expects variable:
# mailing_list:
#   name: str
#   recipients: [str]

# TODO at some point, allow mlmmj-make-ml to create a mailinglist fully on the command line
# to avoid this whole answer file thing.
- name: Create mlmmj-make-ml answer file
  ansible.builtin.template:
    src: mlmmj-answers.txt.j2
    dest: /tmp/mlmmj/mlmmj-answers.txt
    mode: '0600'
    owner: mlmmj
    group: mlmmj

- name: Create mailing list
  ansible.builtin.command: '/usr/local/bin/mlmmj-make-ml -f /tmp/mlmmj/mlmmj-answers.txt'
  register: make_ml_output
  changed_when: make_ml_output.rc == 0

- name: Change relay host to local IPv6
  ansible.builtin.copy:
    dest: '/var/spool/mlmmj/{{ mailing_list.name }}/control/relayhost'
    content: "fe80::eeee:{{ jid }}%lo0\n"
    mode: '0644'
    owner: mlmmj
    group: mlmmj

- name: Subscribe all selected addresses
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/{{ mailing_list.name }} -a {{ item }}@{{ org_domain }} -c -f -s'
  loop: '{{ mailing_list.recipients }}'
  register: mlmmj_sub_output
  changed_when: mlmmj_sub_output.rc == 0
