# TODO at some point, allow mlmmj-make-ml to create a mailinglist fully on the command line
# to avoid this whole answer file thing.
- name: Create mlmmj-make-ml answer file
  ansible.builtin.template:
    src: mlmmj-answers.txt.j2
    dest: /var/spool/mlmmj/mlmmj-answers.txt
    mode: '0644'
    owner: mlmmj
    group: mlmmj

# TODO change to /usr/local/bin after mlmmj release 1.4.0
- name: Create mailing list
  # ansible.builtin.command: '/usr/local/bin/mlmmj-make-ml -f /var/spool/mlmmj/mlmmj-answers.txt'
  ansible.builtin.command: '/var/spool/mlmmj/mymlmmj-make-ml -f /var/spool/mlmmj/mlmmj-answers.txt'
  register: make_ml_output
  changed_when: make_ml_output.rc == 0

- name: Change relay host to local IPv6
  ansible.builtin.copy:
    dest: '/var/spool/mlmmj/{{ org_domain }}/{{ setup_jail_mail_mailinglist_kv.key }}/control/relayhost'
    content: '{{ ansible_host }}'
    mode: '0644'
    owner: mlmmj
    group: mlmmj

- name: Subscribe all selected addresses
  ansible.builtin.command: '/usr/local/bin/mlmmj-sub -L /var/spool/mlmmj/{{ org_domain }}/{{ setup_jail_mail_mailinglist_kv.key }} -a {{ item }}@{{ org_domain }} -c -f -s'
  loop: '{{ setup_jail_mail_mailinglist_kv.value.recipients }}'
  register: mlmmj_sub_output
  changed_when: mlmmj_sub_output.rc == 0
