---
- name: Start fake company
  hosts: jailhost
  vars_files:
    - vars/shared.yml
  tasks:
    # TODO add support in ansible for service module
    - name: Start all jails
      ansible.builtin.command: service jail onerestart # noqa: command-instead-of-module
      changed_when: true

    - name: Add human
      ansible.builtin.include_role:
        name: new_human
      loop: '{{ humans }}'
      loop_control:
        loop_var: human
