---
- name: Add all pre-configured humans
  hosts: jailhost
  vars_files:
    - vars/shared.yml
  tasks:
    - name: Add human
      ansible.builtin.include_role:
        name: new_human
      loop: '{{ humans }}'
      loop_control:
        loop_var: human
