---
- name: Testing playbook
  hosts: jails
  remote_user: ansible
  become: true
  become_method: community.general.doas
  gather_facts: true
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: '{{ ansible_fqdn }}'
