- name: Install ansible CA crypto dependencies
  ansible.builtin.command: 'pkg install -y py39-cryptography'
  tags: always

# TODO waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1325335 for ED25519 support
# generating P-256 keys in the meantime
- name: Create CA private key with password protection
  community.crypto.openssl_privatekey:
    path: '/etc/ssl/{{ ansible_fqdn }}.cakey'
    backup: true
    passphrase: "{{ secret_ca_passphrase }}"
    type: ECC
    curve: secp256r1
    cipher: auto

- name: Create CSR for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: '/etc/ssl/{{ ansible_fqdn }}.cakey'
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    common_name: '{{ ansible_fqdn }} (CA)'
    use_common_name_for_san: false # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: setup_jail_certauth_ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: '/etc/ssl/{{ ansible_fqdn }}.cacrt'
    csr_content: "{{ setup_jail_certauth_ca_csr.csr }}"
    privatekey_path: '/etc/ssl/{{ ansible_fqdn }}.cakey'
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    provider: selfsigned
