- name: Install ansible CA crypto dependencies
  ansible.builtin.command: 'pkg install -y py39-cryptography'
  tags: always

- name: Create CA private key with password protection
  community.crypto.openssl_privatekey:
    path: /etc/ssl/certauth.empt.siva.cakey
    backup: true
    type: Ed25519
    passphrase: "{{ secret_ca_passphrase }}"
    cipher: auto

- name: Create CSR for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/ssl/certauth.empt.siva.cakey
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    common_name: 'certauth.empt.siva (CA)'
    use_common_name_for_san: false # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: /etc/ssl/certauth.empt.siva.cacrt
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: /etc/ssl/certauth.empt.siva.cakey
    privatekey_passphrase: "{{ secret_ca_passphrase }}"
    provider: selfsigned
