- name: Install heimdal port from poudriere
  ansible.builtin.command: 'pkg -r {{ jailroot }} install -y heimdal'
  tags: always

- name: Configure heimdal
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: '{{ jailroot }}/etc/krb5.conf'
    owner: root
    group: wheel
    mode: '0644'
  tags: always

- name: Enable heimdal services
  ansible.builtin.blockinfile:
    path: '{{ jailroot }}/etc/rc.conf'
    marker: ''
    block: |
      {{ item }}_enable="YES"
      {{ item }}_program="/usr/local/libexec/{{ item }}"
  loop:
    - kdc
    - kadmind
  tags: always
