- name: Configure radicale
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/radicale/{{ item.path | replace(".j2", "") }}'
    mode: '0600'
    owner: radicale
    group: radicale
  with_community.general.filetree: '{{ "templates/radicale" }}'
  when: item.state == 'file'

- name: Configure gunicorn to run as 'radicale' user and group
  community.general.sysrc:
    name: 'gunicorn_{{ item }}'
    value: radicale
  loop:
    - user
    - group

- name: Configure gunicorn to run with radicale-owned gunicorn config
  community.general.sysrc:
    name: gunicorn_config
    value: /usr/local/etc/radicale/gunicorn_radicale.conf.py

- name: Change keytab ownership strictly to radicale user
  ansible.builtin.file:
    name: /etc/krb5.keytab
    mode: '0600'
    owner: radicale
    group: radicale

- name: Create missing radicale database directory
  ansible.builtin.file:
    name: /var/db/radicale/collection-root
    state: directory
    mode: '0700'
    owner: radicale
    group: radicale

- name: Enable gunicorn service
  ansible.builtin.service:
    name: gunicorn
    enabled: true
    state: started
