# TODO add upstream /usr/local/etc default config directory
- name: Configure radicale
  ansible.builtin.template:
    src: radicale_config.ini.j2
    dest: /usr/local/etc/radicale/config
    mode: '0600'
    owner: radicale
    group: radicale
