# TODO determine if we should use DHCPv6 instead of random mac + SLAAC for each jail's IP
# TODO automate/loop the individual jail IP generation, especially the random_mac seeds
hostip: '{{ ansible_facts["re0"]["ipv6"] | selectattr("address", "ansible.utils.in_network", "fc00::/7") | first }}'
ula_subnet: '{{ hostip.address | ansible.utils.ipsubnet(hostip.prefix) }}'
all_jails:
  - name: certauth
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: dns
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: kerberos
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: logs
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: mail
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: prometheus
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
  - name: ssh
    ipaddr: '{{ ula_subnet | ansible.utils.slaac("aa:bb:cc" | community.general.random_mac) }}'
