- name: Install required packages from poudriere
  ansible.builtin.command: 'pkg install -y postfix dovecot mlmmj'
  changed_when: true

- name: Create local (unix account) mail directory
  ansible.builtin.file:
    path: /var/mail/local
    state: directory
    mode: '0755'
    owner: root
    group: mail
  tags: always

- name: Add user to handle dovecot virtual mail
  ansible.builtin.user:
    name: vmail
    comment: Virtual Mail Handler
    home: /var/mail/vhosts
    shell: /usr/sbin/nologin
  tags: always
  register: setup_jail_mail_user_vmail

- name: Create dovecot virtual mail destination directories
  ansible.builtin.file:
    path: '/var/mail/{{ item }}'
    state: directory
    mode: '0770'
    owner: vmail
    group: vmail
  loop:
    - vhosts
    - attachments
  tags: always

- name: Create dovecot conf.d/ directory
  ansible.builtin.file:
    path: '/usr/local/etc/dovecot/conf.d'
    state: directory
    mode: '0755'
    owner: root
    group: wheel
  tags: always

- name: Configure dovecot
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/dovecot/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/dovecot" }}'
  when: item.state == 'file'
  tags: always

- name: Configure postfix
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/postfix/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/postfix" }}'
  when: item.state == 'file'

- name: Generate postfix maps
  ansible.builtin.command: 'postmap /usr/local/etc/postfix/{{ item }}'
  loop:
    - transport
    - virtual
    - vmailbox
  register: setup_jail_mail_postmap
  changed_when: setup_jail_mail_postmap.rc == 0

- name: Add user to handle mlmmj postfix transport
  ansible.builtin.user:
    name: mlmmj
    comment: mlmmj transport user
    home: /var/spool/mlmmj
      #shell: /usr/sbin/nologin

# local key just for testing
- name: Add control host's ssh key to mlmmj's authorized keys
  ansible.posix.authorized_key:
    user: mlmmj
    key: "{{ lookup('file', '/home/siva/.ssh/id_ed25519.pub') }}"
    exclusive: true

- name: Create mlmmj spool directory
  ansible.builtin.file:
    path: '/var/spool/mlmmj/{{ ansible_domain }}'
    state: directory
    mode: '0775'
    owner: mlmmj
    group: mlmmj

- name: Enable and start mail services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - postfix
    - dovecot

# TODO remove after mlmmj release 1.4.0
- name: TMP copy prerelease mymlmmj-make-ml script
  ansible.builtin.copy:
    src: mlmmj-make-ml.sh
    dest: /var/spool/mlmmj/mymlmmj-make-ml
    mode: '0755'
    owner: mlmmj
    group: mlmmj

- name: Add mlmmj maintenance task to cron
  ansible.builtin.lineinfile:
    path: /etc/crontab
    line: '*/2 * * * * mlmmj /usr/local/bin/mlmmj-maintd -F -d /var/spool/mlmmj/{{ ansible_domain }}'
