- name: Configure postfix
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/postfix/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/postfix" }}'
  when: item.state == 'file'

# TODO cdb maps and aliases
- name: Generate postfix maps
  ansible.builtin.command: 'postmap /usr/local/etc/postfix/{{ item }}'
  loop:
    - mlmmj_transport
    - mlmmj_aliases
  register: setup_jail_mail_postmap
  changed_when: setup_jail_mail_postmap.rc == 0

- name: Generate aliases database
  ansible.builtin.command: postalias cdb:/etc/mail/aliases
  changed_when: true

- name: Create dovecot conf.d/ directory
  ansible.builtin.file:
    path: /usr/local/etc/dovecot/conf.d
    state: directory
    mode: '0755'
    owner: root
    group: wheel

- name: Configure dovecot
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/dovecot/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/dovecot" }}'
  when: item.state == 'file'

- name: Add mlmmj user for postfix transport
  ansible.builtin.user:
    name: mlmmj
    comment: Mlmmj Transport
    home: /var/spool/mlmmj
    shell: /usr/sbin/nologin
    create_home: false

- name: Create empty mlmmj spool directory
  ansible.builtin.file:
    path: /var/spool/mlmmj
    state: directory
    mode: '0700'
    owner: mlmmj
    group: mlmmj

- name: Enable and start mail services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - postfix
    - dovecot

- name: Add mlmmj maintenance task to cron
  ansible.builtin.lineinfile:
    path: /etc/crontab
    line: '*/2 * * * * mlmmj /usr/local/bin/mlmmj-maintd -F -d /var/spool/mlmmj'
