- name: Install required packages from poudriere
  ansible.builtin.command: 'pkg install -y postfix dovecot mlmmj'
  tags: always

- name: Create local (unix account) mail directory
  ansible.builtin.file:
    path: /var/mail/local
    state: directory
    mode: '0755'
    owner: root
    group: mail
  tags: always

- name: Add user to handle dovecot virtual mail
  ansible.builtin.user:
    name: vmail
    comment: Virtual Mail Handler
    home: /var/mail/vhosts
    shell: /usr/sbin/nologin
  tags: always
  register: setup_jail_mail_user_vmail

- name: Create dovecot virtual mail destination directories
  ansible.builtin.file:
    path: '/var/mail/{{ item }}'
    state: directory
    mode: '0770'
    owner: vmail
    group: vmail
  loop:
    - vhosts
    - attachments
  tags: always

- name: Add user to handle mlmmj postfix transport
  ansible.builtin.user:
    name: mlmmj
    comment: mlmmj transport user
    home: /var/spool/mlmmj
    shell: /usr/sbin/nologin
  tags: always

- name: Create mlmmj spool directory
  ansible.builtin.file:
    path: /var/spool/mlmmj
    state: directory
    mode: '0775'
    owner: mlmmj
    group: mlmmj
  tags: always

- name: Configure postfix
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/postfix/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/postfix" }}'
  when: item.state == 'file'
  tags: always

- name: Generate postfix maps
  ansible.builtin.command: 'postmap /usr/local/etc/postfix/{{ item }}'
  loop:
    - transport
    - virtual
    - vmailbox

- name: Create dovecot conf.d/ directory
  ansible.builtin.file:
    path: '/usr/local/etc/dovecot/conf.d'
    state: directory
    mode: '0755'
    owner: root
    group: wheel
  tags: always

- name: Configure dovecot
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/usr/local/etc/dovecot/{{ item.path | replace(".j2", "") }}'
    mode: '0644'
  with_community.general.filetree: '{{ "templates/dovecot" }}'
  when: item.state == 'file'
  tags: always

- name: Enable and start mail services
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - postfix
    - dovecot
  tags: always
